easy_admin:


    list:
        actions: ['show']
    entities:
#        # List the entity class name you want to manage

        Maisons:
            class: App\Entity\House
            list:
                fields: ['name', 'price_ht', 'categories']

        Categories:
            class: App\Entity\Category

        Product:
          class: App\Entity\Product

        Lot:
          class: App\Entity\Lot

        ContactType:
            class: App\Entity\ContactType

        Contact:
          class: App\Entity\Contact
          list:
              fields:
                  - { property: 'lots', type: array }
                  - { property: 'societe'}
                  - { property: 'nom_prenom', label: 'Nom'}
                  - { property: 'telephone_portable' }
                  - { property: 'email', type: 'email' }
                  - { property: contact_type, label: Type}


    design:
        brand_color: '#3f62a7'
        color_scheme: 'dark'
        assets:
            favicon: '../assets/logofi.jpg'







    site_name: "GROUPE BERDIN ADMIN"