easy_admin:


    list:
        actions:
            - { name: show, icon: search}
            - { name: edit, icon: pencil}
    entities:
#        # List the entity class name you want to manage

        Maisons:
            class: App\Entity\House
            list:
                fields:
                    - { property: name, label: Nom }
                    - { property: price_ht, label: Prix HT }
                    - { property: price_ttc, label: Prix TTC }
                    - { property: categories, type: array }

            form:
                fields:
                    - { property: name, label: Nom }
                    - { property: price_ht, label: Prix HT, type: money }
                    - { property: categories }
                    - { property: products, type: entity }




        HouseProduct:
            class: App\Entity\HouseProduct

        DevisProduct:
            class: App\Entity\DevisProduct

        Devis:
            class: App\Entity\Devis
            form:
                fields:
                    #- { type: 'group', css_class: 'col-sm-3', label: 'Informations' }
                    -
                        property: id
                        type_options: {disabled: true}
                    - name
                    - date

                    #- { type: 'group', css_class: 'col-sm-9', label: 'Produits' }
                    - { property: devisProducts, type: collection, type_options: { entry_type: App\Form\DevisProductType, allow_delete: true, allow_add: true, by_reference: false}}
                    #- { property: name , label: Product, type: entity , type_options: { class: 'App\Entity\Product'  } }
                   # - addDevisProduct

        Users:
            class: App\Entity\User
            form:
                fields:
                    - fullName
                    - username
                    - email
                        # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'password', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        Categories:
            class: App\Entity\Category

        Product:
            class: App\Entity\Product




        Lot:
          class: App\Entity\Lot

        ContactType:
            class: App\Entity\ContactType

        Clients:
            class: App\Entity\Contact
            list:
                dql_filter: entity.contact_type = 4

        Contact:
          class: App\Entity\Contact
          list:
              #dql_filter: entity.contact_type = 1
              max_results: 50


              fields:
                  - { property: 'lots', type: 'simple_array' }
                  - { property: 'societe'}
                  - { property: 'nom_prenom', label: 'Nom' }
                  - { property: 'telephone_portable', type: 'tel' }
                  - { property: 'email', type: 'email' }
                  - { property: contact_type, label: Type}


    design:
        brand_color: '#3f62a7'
        color_scheme: 'dark'
        assets:
            favicon: '../images/logofi.jpg'

        menu:
            - { label: Utilisateurs }
            - { entity: Contact, label: Contacts Pro}
            - { entity: Clients, label: Clients}
            - { entity: Maisons, label: Catalogue Maisons}
            - label: Admin
              children: [Categories, Lot, ContactType, Product, HouseProduct, Users, Devis, DevisProduct]



    site_name: "GROUPE BERDIN ADMIN"