#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout

# app/config/routing.yml
api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional